# port配置
server:
  port: 8022
  address: 0.0.0.0
#数据源配置
spring:
  #文件大小设置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  #数据库资源设置 私密
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml